// const sampleResponse = {
//   "kind": "youtube#videoListResponse",
//   "etag": "s8XXS5axHpYfSWe4fXvRRXBi2NE",
//   "items": [
//     {
//       "kind": "youtube#video",
//       "etag": "tttEOwT_HLHVh0-GDSa7JMXU1Io",
//       "id": "Z0CQf3JDKAY",
//       "snippet": {
//         "publishedAt": "2025-10-28T04:02:27Z",
//         "channelId": "UCo1DYcm1IZ9v3UPkpiAcgtg",
//         "title": "Like Him",
//         "description": "Provided to YouTube by Columbia\n\nLike Him · Tyler, The Creator · Lola Young\n\nCHROMAKOPIA +\n\n℗ 2025 Columbia Records, a Division of Sony Music Entertainment, as exclusive licensee\n\nReleased on: 2024-10-29\n\nAssociated Performer: Tyler, The Creator feat. Lola Young\nProducer, Associated Performer: Tyler, The Creator\nAssociated Performer: Lola Young\nBass: Thundercat\nBackground Vocal: Robert \"RAab\" Stevenson\nBackground Vocal: Justin Levy\nRecording Engineer, Lyricist, Composer, Executive Producer: Tyler Okonma\nEngineer: Vic Wainstein\nMixing Engineer: NealHPogue\nAssistant Engineer: Zachary Acosta\nMastering Engineer: Mike Bozzi\n\nAuto-generated by YouTube.",
//         "thumbnails": {
//           "default": {
//             "url": "https://i.ytimg.com/vi/Z0CQf3JDKAY/default.jpg",
//             "width": 120,
//             "height": 90
//           },
//           "medium": {
//             "url": "https://i.ytimg.com/vi/Z0CQf3JDKAY/mqdefault.jpg",
//             "width": 320,
//             "height": 180
//           },
//           "high": {
//             "url": "https://i.ytimg.com/vi/Z0CQf3JDKAY/hqdefault.jpg",
//             "width": 480,
//             "height": 360
//           },
//           "standard": {
//             "url": "https://i.ytimg.com/vi/Z0CQf3JDKAY/sddefault.jpg",
//             "width": 640,
//             "height": 480
//           },
//           "maxres": {
//             "url": "https://i.ytimg.com/vi/Z0CQf3JDKAY/maxresdefault.jpg",
//             "width": 1280,
//             "height": 720
//           }
//         },
//         "channelTitle": "Tyler, The Creator - Topic",
//         "tags": [
//           "Tyler, The Creator",
//           "Lola Young",
//           "CHROMAKOPIA +",
//           "Like Him"
//         ],
//         "categoryId": "10",
//         "liveBroadcastContent": "none",
//         "defaultLanguage": "en",
//         "localized": {
//           "title": "Like Him",
//           "description": "Provided to YouTube by Columbia\n\nLike Him · Tyler, The Creator · Lola Young\n\nCHROMAKOPIA +\n\n℗ 2025 Columbia Records, a Division of Sony Music Entertainment, as exclusive licensee\n\nReleased on: 2024-10-29\n\nAssociated Performer: Tyler, The Creator feat. Lola Young\nProducer, Associated Performer: Tyler, The Creator\nAssociated Performer: Lola Young\nBass: Thundercat\nBackground Vocal: Robert \"RAab\" Stevenson\nBackground Vocal: Justin Levy\nRecording Engineer, Lyricist, Composer, Executive Producer: Tyler Okonma\nEngineer: Vic Wainstein\nMixing Engineer: NealHPogue\nAssistant Engineer: Zachary Acosta\nMastering Engineer: Mike Bozzi\n\nAuto-generated by YouTube."
//         },
//         "defaultAudioLanguage": "en"
//       }
//     }
//   ],
//   "pageInfo": {
//     "totalResults": 1,
//     "resultsPerPage": 1
//   }
// }


const getVideoDetails = async (videoId) => {
    try {
        const videoParams = {
            part : 'id,snippet,topicDetails',
            id : videoId,
            key : process.env.youtube_API_KEY,
        }
        const queryString = new URLSearchParams(videoParams);
        const response = await fetch(`${process.env.youtube_API}/videos?${queryString}`);
        const responseJSON = await response.json();

        const topicCategories = responseJSON.items[0].topicDetails.topicCategories.map((item) => {
            return item.slice(30);
        }).join("%7C");

        const videoDetails = {
            publishedAt : responseJSON.items[0].snippet.publishedAt.slice(0,10),
            channelId : responseJSON.items[0].snippet.channelId,
            channelTitle : responseJSON.items[0].snippet.channelTitle,
            videoId : responseJSON.items[0].id.videoId,
            videoTitle : responseJSON.items[0].snippet.title,
            thumbnailURL : responseJSON.items[0].snippet.thumbnails.high.url,
            topicCategories : topicCategories,
        }

        return videoDetails;
    }
    catch(error) {
        console.log(error);
    }
}

module.exports = { getVideoDetails };